services:
  postgres:
    container_name: temp_postgres
    image: postgres:18.1
    volumes:
      - postgres_data_temp:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_123
      - POSTGRES_DB=postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 30s
      timeout: 25s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - system_wide_network

  redis:
    container_name: temp_redis
    image: redis:8.4
    mem_limit: 256m
    volumes:
      - redis_data_temp:/data
      - ./redis.conf:/etc/redis/redis.conf
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 25s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - system_wide_network

  migrations-temp:
    image: 545plea/temp:latest
    container_name: temp_migrations
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    command: npx prisma migrate deploy
    restart: no
    networks:
      - system_wide_network

  temp:
    image: 545plea/temp:latest
    container_name: temp
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrations-temp:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/health',
        ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    networks:
      - system_wide_network

volumes:
  postgres_data_temp:
  redis_data_temp:

networks:
  system_wide_network:
    external: true
    name: system_wide_network
